# Generated by Django 5.2.7 on 2025-10-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('0', 'super_admin'), ('1', 'admin'), ('2', 'user')], default='1', max_length=1)),
                ('status', models.CharField(choices=[('0', 'inactive'), ('1', 'active'), ('5', 'deleted')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
