# Generated by Django 5.2.7 on 2025-11-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_company_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
    ]
