# Generated by Django 5.2.7 on 2025-11-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='my_app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_companies', to='my_app.user')),
            ],
            options={
                'db_table': 'company_followers',
                'unique_together': {('company', 'user')},
            },
        ),
    ]
