# Generated by Django 5.2.7 on 2025-11-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_company_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_followers',
            name='followed_at',
        ),
        migrations.AddField(
            model_name='company_followers',
            name='status',
            field=models.CharField(choices=[('0', 'unfollwed'), ('1', 'following'), ('5', 'deleted')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='company_followers',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
