# Generated by Django 5.2.7 on 2025-11-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_company_followers_followed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_followers',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
